implement statistic service
Avseenkov/java-explore-with-me pull request #3
Opened 2023-05-31 18:48 UTC by Avseenkov

2023-06-02 07:23 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Но есть некоторое количество замечаний, которое необходимо исправить!

Желаю удачи!

2023-06-02 07:23 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/main/MainApplication.java
> +    }
А это точно надо, и если да, то неплохо было бы написать пояснение зачем.

2023-06-02 07:23 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/main/Test.java
> +}
Довольно странный класс, хотелось бы увидеть пояснения

2023-06-02 07:23 UTC, LexLippi commented on statistics/statistics_shared/src/main/java/ru/practicum/dto/RequestDTO.java
> +    Long id;
Почему у этого поля нет модификатора доступа?

2023-06-02 07:23 UTC, LexLippi commented on statistics/statistics_server/src/main/resources/schema.sql
> +    timestamp    timestamp default now()                 NOT NULL
по возможности лучше не называть поля также, как и типы данных

2023-06-02 07:23 UTC, LexLippi commented on statistics/statistics_server/src/main/java/ru/practicum/services/RequestServiceImpl.java
> +        }
можно использовать тернарный оператор, чтобы не пришлось отделять объявление от инициализации

2023-06-02 13:05 UTC, Avseenkov commented on ewm-service/src/main/java/ru/practicum/main/MainApplication.java
> +    }
Это тестовые данные, просто проверял, что клиент работает.

2023-06-02 13:05 UTC, Avseenkov commented on ewm-service/src/main/java/ru/practicum/main/Test.java
> +}
Это тестовые данные, просто проверял, что клиент работает.

2023-06-03 10:59 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/main/MainApplication.java
> +    }
Ну их стоит удалять тогда :)

2023-06-03 11:03 UTC, LexLippi requested changes
Привет!

Отличная работа!

Осталось пару комментариев!

Желаю удачи!

2023-06-03 11:03 UTC, LexLippi commented on statistics/statistics_server/src/main/java/ru/practicum/model/Request.java
> +    public String uri;
А кстати почему все эти поля публичные, если у нас есть `Getter` и `Setter`?

2023-06-03 11:03 UTC, LexLippi commented on statistics/statistics_server/src/main/java/ru/practicum/services/RequestServiceImpl.java
> +        JPAQuery<RequestResponseDTO> jpaQuery = queryFactory.from(QRequest.request)
А кстати зачем тебе для этого отдельная переменная?

Можно же сразу здесь `return` сделать, она не слишком информативна, и кажется, можно не разбивать жто на переменную и возврат значения

2023-06-03 11:03 UTC, LexLippi commented on statistics/statistics_shared/src/main/java/ru/practicum/dto/RequestDTO.java
> +    public String uri;
Аналогично непонятно почему модификаторы публичные, если есть `Getter` и `Setter`

2023-06-05 07:33 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи при реализации следующих частей дипломного проекта!

2023-06-05 07:46 UTC, merged