implement main service
Avseenkov/java-explore-with-me pull request #4
Opened 2023-06-13 09:05 UTC by Avseenkov

2023-06-14 09:16 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые надо исправить!

Желаю удачи!

2023-06-14 09:16 UTC, LexLippi commented on ewm-service/src/main/resources/schema.sql
> +    lon                  REAL                                                NOT NULL,
Я бы посоветовал использовать `FLOAT` или `DOUBLE PRECISION`

2023-06-14 09:16 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/main/service/stats/StatsService.java
> +        }
лучше использовать конструкцию `.map().orElse()`

2023-06-14 09:16 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/main/controller/pub/CompilationPublicController.java
> +            @RequestParam(required = false, defaultValue = "false") boolean pinned,
Когда есть `defaultValue` нет необходимости в `required`

2023-06-16 07:47 UTC, Avseenkov commented on ewm-service/src/main/java/ru/practicum/main/service/stats/StatsService.java
> +        }
Не совсем понял зачем использовать такую конструкцию в этом случае, можешь подсказать?

2023-06-16 11:15 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/main/service/stats/StatsService.java
> +        }
Проблема в том, что в данном случае ты используешь `.get ` у `Optional`-объекта. Это почти всегда плохо, потому, что преимущество `Optional`-объекта в том, что его вычисления ленивые, а когда мы вызываем у него метод `get` мы по сути требуем выполнить запрос, чего не хотелось бы. 

Поэтому при работе с `Optional` мы стараемся избегать вызовов `get` насколько это вохможно. В данном случае это можно решить с помощью той конструкции, которую я предложил

Тут написано почему это не очень
https://www.baeldung.com/java-optional#get

2023-06-16 11:16 UTC, LexLippi approved these changes
Привет!

Хорошая работа!
Я ее приму, но лучше исправить `get` к следующей части

Желаю удачи!

2023-06-17 08:19 UTC, merged